### PR TITLE
Migrate to HTTP2

### LINKED ISSUE #4: Canvas parsed as a Node
Thanks for implementing all of this! It is a time saver!

When parsing the document, all canvas are of type `Node` instead of `Canvas` (for pages in documents). It's then impossible to access to their children.

image

I guess that must be a parsing error.

### LINKED ISSUE #5: Error 400: Bad Request
Hello! I am currently trying to use the Figma API endpoint with dart. 
I have tried using the `http` package as follows: 
`await http.get("https://api.figma.com/v1/files/2wRuvMlEmTeAjyCvET9DtB", headers: {
        'X-Figma-Token': '64232-6cc246bc-05ce-44fc-88c4-5e221a87ab1a',
  });
`
I have also tried to use the Dio package as follows:
`
Response tempResponse = await dio.get(
    'https://api.figma.com/v1/files/2wRuvMlEmTeAjyCvET9DtB',
    options: Options(
    headers: {
        'X-Figma-Token': '64232-6cc246bc-05ce-44fc-88c4-5e221a87ab1a',
    },
    ),
);
`
Finally, I tried to use the Figma dart package as follows:
`
final client = FigmaClient('64232-6cc246bc-05ce-44fc-88c4-5e221a87ab1a');
      await client.getFile('2wRuvMlEmTeAjyCvET9DtB').then((value) {
        print(value);
});
`

In all three cases, I get a 400, bad request error.

The weird thing is that when trying to do a curl request through the terminal it works fine. Is this an issue specifically with dart? 
Thank you for the help.

### PR DESCRIPTION
**Pull request by arnemolland**
Originally #6 , resolves #5, resolves #4

### CODE REVIEW

**Comment by aloisdeniel** [comment]
Thanks for your reactivity! Really appreciate. 

This package will become a must-have IMO.

**Comment by aloisdeniel** [comment]
One question through : if I'm right you removed the `StyleTypeKey` which was needed since it is different from `StyleType` when used as key of style dictionaries(they are lowercase, and moreover it has `stroke` value). Is there a new solution to this issue that I'm missing ?

**Comment by arnemolland** [comment]
@aloisdeniel No problem! There's a lot of potential for features built upon the Figma API, if you have anything in mind please let me know if you're interested in collaborating on this.

**Comment by aloisdeniel** [comment]
I'm currently using this package to build code generators around Figma API ([theme generator](https://github.com/aloisdeniel/figma-to-flutter/tree/master/figma_theme_generator) and a rewrite of my component generator).

So, I might have suggestions, and help you in the future! :)

**Pull request merged**
