### PR TITLE
Add missing 'PDF' export format.

### PR DESCRIPTION
**Pull request by aloisdeniel**

### CODE REVIEW

**Comment by arnemolland** [comment]
Thanks for the PR! Do you mind committing the generated file as well? I'll merge this asap.

**Comment by aloisdeniel** [comment]
Yes, I'm struggling with my environnement right now. Since last Flutter version, the build_runner task hangs ... But as soon as I found a solution I commit it!

**Comment by aloisdeniel** [comment]
Done!

**Review by arnemolland — COMMENTED** [review]
LGTM

**Pull request merged**
